export const SET_WISHLIST = "SET_WISHLIST";
export const SET_LENDING_LIBRARY = "SET_LENDING_LIBRARY";
export const SET_USER_BOOKS = "SET_USER_BOOKS";
export const SET_USER_BOOKS_IDS = "SET_USER_BOOKS_IDS";
export const SET_WISHLIST_IDS = "SET_WISHLIST_IDS";